# Generated by Django 2.2.16 on 2022-08-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20220718_2012"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confirmation_code",
            field=models.TextField(
                blank=True, verbose_name="Код подтверждения"
            ),
        ),
    ]
