# Generated by Django 2.2.16 on 2022-09-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20220903_1951"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="confirmation_code",
        ),
    ]
