# Generated by Django 2.2.16 on 2022-08-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_auto_20220828_1722"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="title",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.TextField(verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.IntegerField(verbose_name="Год выпуска"),
        ),
    ]
