# Generated by Django 2.2.16 on 2022-08-29 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_auto_20220828_1728"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="title",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="title_comments",
                to="reviews.Title",
            ),
            preserve_default=False,
        ),
    ]
