# Generated by Django 2.2.16 on 2022-08-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_auto_20220830_1423"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="name",
            field=models.TextField(verbose_name="Название"),
        ),
    ]
