# Generated by Django 2.2.16 on 2022-08-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0008_remove_comment_title"),
        ("reviews", "0007_auto_20220830_1425"),
    ]

    operations = []
