# Generated by Django 2.2.16 on 2022-09-03 16:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_auto_20220830_1504"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=256, verbose_name="Название категории"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                unique=True, verbose_name="slug названия категории"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор комментария",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                verbose_name="Дата публикации",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_comments",
                to="reviews.Review",
                verbose_name="Ревью",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(verbose_name="Текст комментария"),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(
                max_length=256, verbose_name="Название жанра"
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="slug",
            field=models.SlugField(
                unique=True, verbose_name="slug Названия жанра"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор ревью",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Оценка не может быть меньше единицы"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, message="Оценка не может быть больше десяти"
                    ),
                ],
                verbose_name="Оценка",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(verbose_name="Текст ревью"),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="title_reviews",
                to="reviews.Title",
                verbose_name="Название произведения",
            ),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.IntegerField(
                validators=[reviews.validators.validate_year],
                verbose_name="Год выпуска",
            ),
        ),
    ]
