# Generated by Django 2.2.16 on 2022-09-03 18:37

from django.db import migrations, models

import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0011_auto_20220903_1931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.SmallIntegerField(
                validators=[reviews.validators.validate_year],
                verbose_name="Год выпуска",
            ),
        ),
    ]
