# Generated by Django 2.2.16 on 2022-09-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0011_auto_20220903_1951"),
        ("reviews", "0012_auto_20220903_2137"),
    ]

    operations = []
